project:
  type: website
  output-dir: docs 

website:
  title: "Programming for Engineers and Scientists"
  sidebar:
    style: "floating"
    contents:
      - section: "Course Info"
        contents:
          - index.qmd
          - conventions.qmd
          - Managing Python Installations.qmd
      - section: "Lectures"
        contents:
          - lectures/01_course_introduction/course_intro_and_python_environment.qmd
          - lectures/02_variables_arithmetic_basic_i_o/variables_arithmetic_basic_i_o.qmd
          - lectures/03_strings_lists_tuples/strings_lists_tuples.qmd
          - lectures/04_vectors_and_numpy/vectors_and_numpy.qmd
          - lectures/05_functions/functions.qmd
          - lectures/06_basic_plotting/basic_plotting.qmd
          - lectures/07_boolean_logic/boolean_logic.qmd
          - lectures/08_control_structures/control_structures.qmd
          - lectures/09_for_loops/for_loops.qmd
          - lectures/10_while_loops/while_loops.qmd
          - lectures/11_nested_loops/nested_loops.qmd
          - lectures/12_matrices/matrices.qmd
          - lectures/13_dictionaries/dictionaries.qmd
          - lectures/14_sets/sets.qmd
          - lectures/15_exceptions_and_files/exceptions_and_files.qmd
          - lectures/16_pandas/pandas.qmd
          - lectures/17_objects_and_classes/objects_and_classes.qmd
          - lectures/18_distance_and_similarity/distance_and_similarity.qmd

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    html-math-method: katex
    code-copy: true

editor: visual