---
title: "1: Course Introduction and the Python Environment"
format: html
---

# Programming

This course is about problem solving using computers. Problem solving means the ability to formulate problems, think creatively about solutions, and express a solution clearly and accurately. The process of learning to program is an excellent opportunity to practice problem solving skills.

Having a computer solve a problem requires the creation of a set of instructions, a **program**. A **program** is a sequence of instructions that specifies how to perform a computation. An individual instruction is referred to as a **statement**. And so a program is a collection of statements.

The computation might be something as complex as rendering an html page in a web browser or encoding a video and streaming it across the network. It can also be a symbolic computation, such as searching for and replacing text in a document or (strangely enough) compiling a program.

The process of creating these instructions is **programming** .

## Algorithms

If problem solving is a central part of computer science, then the solutions that you create through the problem solving process are also important. In computer science, we refer to these solutions as **algorithms**. 

An algorithm is a step-by-step list of instructions that if followed exactly will solve the problem under consideration. Our goal is to take a problem and develop an algorithm that can serve as a general solution. Once we have such a solution, we can use our computer to automate the execution.

Programming is a skill that allows us to take an algorithm and represent it in a notation (a program) that can be followed by a computer. These programs are written in **programming languages** .

# How Computers Store Data

All data in a computer is stored in sequences of 0s and 1s. This is the binary number system.

A **bit** represents one of two values, 0 or 1 and is the most basic unit of the binary number system.

A **byte** stores eight bits and is just enough memory to store a letter or small number. To store larger data, we use multiple bytes.

To store negative numbers and real numbers, computers use special encoding schemes to represent the added complexity.

- Numbers are often encoded using one bit to determine if the number is positive or negative.
- Real numbers are encoded using floating-point notation.

## Storing Characters

All characters are converted to a numeric code and this numeric code is stored in memory.

The most fundamental coding scheme is ASCII but it is limited to only 128 different characters.

A more modern replacement is called Unicode which is both compatible with ASCII and can represent many more characters.

## Other Types of Data

The word digital describes anything that stores data as binary numbers

For example digital images are composed of pixels. And to store these images, each pixel is converted to a binary number representing the pixel’s color.

Similarly, digital music is composed of sections called samples. To store this music, each sample is converted to a binary number.

# Keywords, Operators, and Syntax

**Keywords** are predefined words used to write a program in a high-level language (a language like Python). Each keyword has specific meaning.

**Operators** perform operations on data. For example, math operators like `+` perform arithmetic (addition in this case).

**Syntax** is a set of rules to be followed when writing program. These rules define how and when keywords and operators can be used to actually construct a program.

# Debugging

Programming is a complex process. Since it is done by human beings, errors may often occur.

Programming errors are called **bugs** and the process of tracking them down and correcting them is called **debugging** . Some claim that in 1945, a dead moth caused a problem on relay number 70, panel F, of one of the first computers, and the term **bug** has remained in use since.

One of the most important skills you will acquire is debugging. Debugging is like an experimental science. Once you have an idea what is going wrong, you modify your program and try again. If your hypothesis was correct, then you can predict the result of the modification, and you take a step closer to a working program. If your hypothesis was wrong, you have to come up with a new one.

## Type of Errors

Three kinds of errors can occur in a program: 

- Syntax Errors
- Runtime Errors
- Semantic Errors

## Syntax Errors

Python can only execute a program if the program is syntactically correct ; otherwise, the process fails and returns an error message.  **Syntax** refers to the structure of a program and the rules about that structure.

For example, in English, a sentence must begin with a capital letter and end with a period. If there is a single syntax error anywhere in your program, Python will display an error message and quit. You will not be able to complete the execution of your program.

During the first few weeks of your programming career, you will probably spend a lot of time tracking down syntax errors. However, as you gain experience, you will make fewer errors, and you will also be able to find your errors faster.

## Runtime Errors

The second type of error is a runtime error, so called because the error does not appear until you run the program. These errors are also called **exceptions** because they usually indicate that something exceptional (and bad) has happened. Runtime errors are rare in the simple programs you will see in the first few chapters, so it might be a while before you encounter one.

## Semantic Errors

If there is a semantic error in your program, it will run successfully in the sense that the computer will not generate any error messages. However, your program will not do the right thing. It will do something else. Specifically, it will do exactly what you told it to do.

The problem is that the program you wrote is not the program you wanted to write. The meaning of the program (its semantics) is wrong.\
Identifying semantic errors can be tricky because it requires you to work backward by looking at the output of the program and trying to figure out what it is doing.

# Formal and Natural Languages

**Natural languages** are the languages that people speak, such as English, Spanish, and French. They were not designed by people (although people try to impose some order on them); they evolved naturally.

**Formal languages** are languages that are designed by people for specific applications. For example, the notation that mathematicians use is a formal language that is particularly good at denoting relationships among numbers and symbols.

Programming languages are formal languages that have been designed to express computations. Formal languages tend to have strict rules about syntax.

For example, $3+3=6$  is a syntactically correct mathematical statement, but $3=+6$ is not.

Syntax rules come in two types, pertaining to **tokens** and structure. **Tokens** are the basic elements of the language, such as words, numbers, and chemical elements. One of the problems with  $3=+6$  is that $=+$ is not a valid token in mathematics (that is, it is not defined for common use).

- The second type of syntax rule pertains to the **structure** of a statement.
  - This is the way the tokens are arranged.
- The statement $3=+6$ is structurally illegal because you cannot place a plus sign immediately after an equal sign.

## Parsing and Semantics

When you read a sentence in English or a statement in a formal language, you have to figure out what the structure of the sentence is. This process is called **parsing**. For example, when you hear the sentence, “The other shoe fell”, you understand that the other shoe is the subject and fell is the verb. Once you have parsed a sentence, you can figure out what it means, or the **semantics** of the sentence.

## Differences between Formal and Natural Languages

Although formal and natural languages have many features in common like tokens, structure, syntax, and semantics, there are substantial differences.

- **Ambiguity**

  - Natural languages are full of ambiguity, which people deal with by using contextual clues and other information.
  - Formal languages are designed to be nearly or completely unambiguous, which means that any statement has exactly one meaning, regardless of context.

- **Redundancy**

  - In order to make up for ambiguity and reduce misunderstandings, natural languages employ lots of redundancy.
  - As a result, natural languages are often verbose. Formal languages are less redundant and more concise.

- **Literalness**

  - Formal languages mean exactly what they say.
  - Natural languages are full of idiom and metaphor.
  - If someone says, “The other shoe fell”, there is probably no shoe and nothing falling.

# Using Python

Python must be installed and configured prior to use.

One of the items installed is the Python interpreter which has two modes of use:

- Interactive mode: enter statements step-by-step like you would on a calculator
- Script mode: save statements in Python script

## Interactive Mode

When you start Python in interactive mode, you will see a prompt. This indicates the interpreter is waiting for a Python statement to be typed.

The prompt reappears after previous statement is executed and (in general) an error message displayed if you incorrectly type a statement.

Interactive mode is a good way to quickly practice simple new parts of Python but becomes cumbersome quickly for more complicated tasks.

## Writing Python Programs and Running Them in Script Mode

For our course we will use script mode which allows us to save programs for future purposes.

To create a program, use script mode:

- Save a set of Python statements in a file
- The filename should have the `.py` extension
- To run the file, or script, type `python filename`at the operating system command line or open the file through your IDE

## Basic Programming Instructions

- **Input**
  - Get data from the keyboard, a file, or some other device.
- **Output**
  - Display data on the screen or send data to a file or other device.
- **Math and Logic**
  - Perform basic mathematical operations like addition and multiplication and logical operations like and, or, and not.
- Conditional execution
  - Check for certain conditions and execute the appropriate sequence of statements.
- Repetition
  - Perform some action repeatedly, usually with some variation.

These basic instructions comprise nearly everything used in programming.

Every program you have ever used, no matter how complicated, is made up of instructions that look like these. 

We can describe programming as the process of breaking a large, complex task into smaller and smaller subtasks until the subtasks are simple enough to be performed with sequences of these basic instructions.

## Hello World

Traditionally, the first program written in a new language is called **Hello, World** because all it does is display the words, Hello, World.

::: core-box
This is an example of using the `print` function, which displays a value on the screen.

```{python}
print('Hello world')
```
:::

The print function will be one of the most common functions we use in this course as it is extremely useful for seeing what it happening step-by-step as your program executes.

## Comments

As programs get bigger and more complicated, they get more difficult to read. Formal languages are dense, and it is often difficult to look at a piece of code and figure out what it is doing, or why.

For this reason, it is a good idea to add notes to your programs to explain in natural language what the program is doing. These notes are called comments.

A **comment** in a computer program is text that is intended only for the human reader, it is completely ignored by the interpreter.

::: core-box
In Python, the **\#** token starts a comment. The rest of the line is ignored. Here is a new version of **Hello, World!**.

```{python}
print('Hello world') #This is a comment
```
:::