---
title: "2: Variable, Arithmeti and Basic I/O"
format: html
---

# Variables

A **variable** is a name that represents a value stored in memory. Variables are used to access and manipulate data stored in these memory locations.

## Assignment

An **assignment** is the process that is used to create a variable and make it reference data (or reference different data if the variable already exists).

The general format of an assignment statement is:

::: core-box
The general format for assignment is:

```         
variable_name = expression
```
:::

For example:

```{python}
mass = 50
```

This sets the variable *`mass`* to the value *`50`*.

Be careful not to confuse the assignment operator `=` with the equals sign. In Python, this symbol is used for assignment. When we reach conditional statements in the future, we will see that the equality operator (which asks the questions are two objects equal) is the double equals sign `==`.

Note that in our examples, the variable receiving the value is always on the left side. This is a general rule in Python, the variable that takes on the value must be on the left.

We also can only use a variable if there is a value actually assigned to it.

```         
number = 
```

The code above here is broken, as the variable named *number* is not assigned to anything. This will cause a syntax error.

### Multiple Assignment

You can also assign values to multiple variables in a single statement. This is known as multiple assignment.

The following code blocks are functionally equivalent:

```{python}
x, y, z = 0, 1, 2
```

```{python}
x = 0
y = 1
z = 2
```

## Data Types

The purpose of data types is to categorize the value located in memory.

The major types in Python are:

- `int` for integer

- `float` for a real number

- `str` for sequences of characters called strings

  - These can be any kind of symbol from letters to numbers to punctuation and more

- `bool` for Boolean values (`True` or `False`)

Some operations behave differently depending on the data type (or may not even be defined at all). For example, the `+` operator performs standard addition when used on integers and floats but instead performs concatenation when used with two strings.

## Copying by Value and Copying by Reference

This example demonstrates the idea of copying by value.

```{python}
x = 7
y = x
x = 10
print(y)
```

- y gets the value of x at the time of assignment
- Changing x later does not change y
- y still prints 7

For simple data types (numbers, strings, Booleans), assignment behaves like copying a value.

With more complex data types (like lists which will be introduced soon), variables behave differently.

The assignment shares access to the same data. The variable names point to a location that holds a single instance of the data. If you change the data through one variable, it will be reflected to all the other variables that point at the same underlying data.

- For simple types (`int`, `float`, `str`, `bool`) assignment copies the value.

- For complex types (lists and many others which will be seen in the future) assignment shares access to the same data.

## Variable Naming Rules

Python has a set of rules for naming variables. Most of these if ignored will result in a syntax error.

- Variable name cannot be a Python keyword
- Variable name cannot contain spaces
- First character must be a letter or an underscore
- After first character may use letters, digits, or underscores
- Variable names are case sensitive

In general, a variable's name should reflect its use. This makes finding and fixing problems in your code much easier. Note that it is common for certain variables to have very simple names (`i`, `j`, `k`, etc.) when they are used for certain common operations. When starting out, you may want to use a more descriptive name to help your understanding.

## Reassigning Variables to a Different Type

We know that variables can reference different values while program is running. This is another way of saying we can reassign variables.

Howver, Python does not check to see if your variable’s type is valid for what you are trying to do (this differs from some other programming languages). If you reassign a variable to a different type, you could break code that was previously working.

Also, in Python, you do not need to worry about deleting variables after they have been used (like some other programming languages). Values that are no longer referenced by variables are automatically removed by Python’s garbage collector.

## Casting

Casting is the process of converting on type of data to another. In Python this is accomplished by a set of functions that is built directly into the language.

| Function | Description | Example | Output |
|------------------|-------------------|------------------|------------------|
| int() | Converts to an integer. Truncates floats towards zero. | int(3.8)<br>int("4") | 3<br>4 |
| float() | Converts to a floating-point number. | float(3)<br>float("3.14") | 3<br>3.14 |
| str() | Converts almost any object into its string representation. | str(100) | "100" |
| bool() | Converts to a boolean (True or False). | bool(1)<br>bool("") | True<br>False |

There are certain restrictions on casting in Python that will cause a runtime error if ignored.

- Non-Numeric Strings to Numeric Types

  - Attempting to cast a string that does not look like a number will raise a ValueError.

    - `int("apple")`

- Casting Float-like Strings to Integers

  - Python cannot directly cast a string containing a decimal point straight into an integer.

    - `score = int("98.6")`

## Avoiding Magic Numbers

A **magic number** is an unexplained numeric value that appears in a program's code.

For example:

```         
amount = balance * 0.065
```

The value *`0.065`* is not specified as to what it actually is. It could be an interest rate, or a fee percentage, or many other possible things. Only the person who wrote the code knows for sure (assuming they remember).

If a magic number is used in many places in a program it can take substantial effort to find and change the number in each location. You take the risk of making a mistake each type you type the magic number the program's code. This can be the source of difficult to find and frustrating errors.

### Named Constants

Rather than using magic numbers, you should used a variable whose purpose is to represent the value. This variable is not intended to be changed during the program and so is called a *constant*. In practice, Python will allow you to change the value, so it is important to remember that this variable is supposed to be static. The common convention in Python is to use all caps to indicate a constant variable.

```{python}
INTEREST_RATE = 0.051
```

## The None Type

`None` is a special Python value that represents no value assigned yet. Note that `None` is a value (not an error). Its data type is a unique `NoneType`.

`None` is used as a placeholder when a value is unknown or not available.

`None` is not the same as:

- `0` (a number)

-  `""` (an empty string)

- `False` (a Boolean)

We use `None` to:

- Initialize a variable before it has a real value

- Represent missing or unknown information

- Indicate that a result has not been computed yet

Rule to remember: Do not perform math or string operations on `None`. Any of these operations causes an error.

# Input, Processing and Output

Typically, a computer performs a three-step process:

- Receive input
  - Input: any data that the program receives while it is running
- Perform some process on the input
  - Example: mathematical calculation
- Produce output

## The `print` Function

We have already seen the `print` function in the *Hello World* example. The `print` function will be one of the most commonly used functions throughout this course. It is extremely useful when trying to debug code, as you can see the contents of variables as your program progresses through its instructions.

### Program Execution Order

In general, statements execute in the order that they appear. Specifically, the go from top (first) to bottom (last). In the future we will see ways of repeating or skipping sections of code.

The output of the following example is '`one`' then '`two`' then '`three`'.

```{python}
print('one')
print('two')
print('three')
```

### Displaying Multiple Items with the Print Function

Python allows one to display multiple items with a single call to print.

-  Items are separated by commas when passed as arguments.

- Arguments displayed in the order they are passed to the function.

- Items are automatically separated by a space when displayed on screen.

```{python}
print('one', 'two', 'three')
```

Based off the previous examples we can see that successive print statements place their value(s) on different lines. This is because the print function puts a newline character at the end of printed data. We can change this default newline to a value of our choice using the special argument *end*.

The following example changes the default newline to a space.

```{python}
print('one',end=' ')
print('two',end=' ')
print('three',end=' ')
```

Similarly, for multiple items displayed on the same line, we can use the separator argument *sep* to change the default space to something else.

The following example changes the default space to a dash.

```{python}
print('one', 'two', 'three',sep='-')
```

Both of these options can be useful to help format printed values to make reading their output easier.

### Newlines and Tabs

Certain special characters are preceded by a backslash `\`.

These characters are treated as commands inside a string.

To create a newline, we use the character `\n`.

Note the extra new line in the following example.

```{python}
print('Hello world\n')
print('Hello world')

```

To create a tab, we use `\t`.

Note the increased whitespace (the tab character) between the words *Hello* and *world*.

```{python}
print('Hello\tworld')

```

We can also see that there is no additional space here in the string *`Hello\tworld`* and yet the tab is still correctly placed. If we included space between the tab and the other parts of the string like:

```{python}
print('Hello \t world')

```

We see that there is additional space in the printed output. This is an important feature of printing strings in that anything inside the string is printed exactly as it is written. By adding the spaces to make things easier for us to read inside the string, we altered the output.

## The `input` Function

Many programs need to read input from the user. While many kinds of data can be used as input, we will largely be dealing with the simple input function and working with text data. More complicated kinds of input tend to require more effort to both read and process, so we will avoid these in an introductory course.

The input function displays an optional prompt and then reads input from the keyboard.

::: core-box
```         
variable_name = input("Your Prompt Here")
```
:::

Note that the input function always returns the data as a *string*. The prompt is typically a string instructing user to enter a value.

Note that the input function also does not automatically display a space after the prompt.

For example:

```         
name = input("What is your name?  ")
```

The above does the following:

- Displays the string 'What is your name? '
- Reads input, as a string, from the keyboard
- Assigns the string that was read from the keyboard to the name variable

### Reading Numbers with the `input` Function

Since the `input` function always returns a string, if we want to use the input as a number in calculations we will need to cast the string to the appropriate numerical type.

```         
number = int(input('Enter a number: '))
```

The above does the following:

- Displays the string *'Enter a number: '*
- Reads input, as a string, from the keyboard
- Converts the input to an int
- Assigns the resulting int to the number *variable*

# Arithmetic Calculations

A **math expression** is a statement that performs a calculation and results in a value.

A **math operator** is a symbol that represents a specific type mathematical operation.

**Operands** are the values associated with an operator. In Python, variables can be operands.

In general, the resulting value of a math expression is typically assigned to a variable.

The following expression has *+* as the operator with the operands of *1* and *y*.

```         
x = 1 + y
```

## Common Math Operators

| Symbol | Operation | Description |
|------------------|-------------------------|-----------------------------|
| \+ | Addition | Standard Arithmetic Addition |
| \- | Subtraction | Standard Arithmetic Subtraction |
| \* | Multiplication | Standard Arithmetic Multiplication |
| / | Division | Floating Point Division |
| // | Integer Division | Division that returns only a whole number (no remainder) |
| \% | Remainder (Modulus) | Division that returns only the remainder |
| \*\* | Exponentiation | Raises number to a power |

### Operator Precedence

Python has rules for operator precedence that are very close to that of normal arithmetic. Higher precedence operators are performed first and operators with the same precedence execute from left to right.

1.  Operations enclosed in parenthesis.
2.  Exponentiation.
3.  Multiplication, Floating Point Division, Integer Division, Remainder.
4.  Addition, Subtraction

### Converting Math Formulas into Python

In Python, an operator is required for any mathematical operation.

Standard mathematical notation like $xy$ where it is implicitly understood that $x$ and $y$ are multiplied together is not allowed in Python. Any mathematical operation needs to be explicitly defined using operators.

In general, converting math formulas into Python tends to require adding multiplication operators and the insertion of parentheses.

### Mixed-Type Expressions and Automatic Type Conversion

The data type resulting from mathematical operations depends on the type of operands.

- Two `int` operands results in another `int`

<!-- -->

- Two `float` operands results in another `float`

<!-- -->

- One `int` operands and one `float` operand results in a `float`