---
title: "3: Strings, Lists and Tuples"
format: html
---

## Strings, Lists, and Tuples

CSCI – 1056

Content Modified from Pearson’s Starting Out with Python 6th Edition

## Strings and String Literals

- **String: sequence of characters that is used as data**

  - A string is a type of data.
  - For example, name = input(“Enter a name”)the variable **name** is a string.

- **String literal: string that appears in actual code of a program**

  - In the above example “Enter a name” is a string literal.

## String Concatenation (1 of 2)

- **To append one string to the end of another string**
- **Use the + operator to concatenate strings**

\>\>\> message = 'Hello ' + 'world'

\>\>\> print(message)

Hello world

\>\>\>

## String Concatenation (2 of 2)

- **You can use string concatenation to break up a long string literal**

print('Enter the amount of ' +

'sales for each day and ' +

'press Enter.')

- **This statement will display the following:**

Enter the amount of sales for each day and press Enter.

## Strings Are Immutable (1 of 2)

- **Strings are immutable**

  - Once they are created, they cannot be changed

    - Concatenation does not change the existing string, but rather creates a new string and assigns the new string to the previously used variable

  - Cannot use an expression of the form

  - *string*\[*index*\] = *new_character*

    - Statement of this type will result in an error

## Strings Are Immutable (2 of 2)

**Figure 8-4** The string 'Carmen' assigned to name

Name = single quote Carmen single quote. name extends right to a box with text that reads, Carmen.

**Figure 8-5** The string 'Carmen Brown' assigned to name

An illustration depicts a string assigned to a name. For long description in Notes pane, press F6.

> Name = name + single quote Brown single quote. name extends right to a box with text that reads, Carmen Brown. Another box above this box contains text that reads, Carmen.

## Displaying Formatted Output With f-Strings (1 of 8)

- **An f-string is a special type of string literal that is prefixed with the letter f**

\>\>\> print(f'Hello world')

Hello world

- **f-strings support placeholders for variables**

\>\>\> name = 'Johnny'

\>\>\> print(f'Hello {name}.')

Hello Johnny.

## Displaying Formatted Output With f-Strings (2 of 8)

- **Placeholders can also be expressions that are evaluated**

\>\>\> print(f'The value is {10 + 2}.')

The value is 12.

\>\>\> val = 10

\>\>\> print(f'The value is {val + 2}.')

The value is 12.

## Displaying Formatted Output With f-Strings (3 of 8)

- **Format specifiers can be used with placeholders**

\>\> num = 123.456789

\>\> print(f'{num:.2f}')

123.46

\>\>\>

- .**2f means:**

  - round the value to 2 decimal places
  - display the value as a floating-point number

## Displaying Formatted Output With f-Strings (4 of 8)

- **Other examples:**

\>\> num = 1000000.00

\>\> print(f'{num:,.2f}')

1,000,000.00

\>\>\> discount = 0.5

\>\>\> print(f'{discount:.0%}')

50%

## Displaying Formatted Output With f-Strings (5 of 8)

- **Other examples:**

\>\> num = 123456789

\>\> print(f'{num:,d}')

123,456,789

\>\>\> num = 12345.6789

\>\>\> print(f'{num:.2e}')

1.23e+04

## Displaying Formatted Output With f-Strings (6 of 8)

- **Specifying a minimum field width:**

A computer code has 3 lines. For long description in Notes pane, press F6.

> The lines read as follows. Line 1. greater than sign greater than sign greater than sign n u m equals 12345 period 6789. Line 2. greater than sign greater than sign greater than sign print left parenthesis f single quote The number is left brace n u m colon 12 comma period 2 f right brace single quote right parenthesis. The number 12 in this line of code is labeled, field width equals 12. Line 3. The number is 12 comma 345 period 68. The number is 12,345.68, where 12,345.68 is entered in a block of field width equals 12.

## Example

print(f'The number is {num:14,.2f}')

*The number is 12,345.68*

print(f'The number is {num:10,.2f}’)

*The number is 12,345.68*

## Displaying Formatted Output With f-Strings (7 of 8)

- **Aligning values within a field**

  - Use \< for left alignment
  - Use \> for right alignment
  - Use \^ for center alignment

- **Examples:**

  - print(f'{num:\<20.2f}')
  - print(f'{num:\>20.2f}')
  - print(f'{num:\^20.2f}')

## Example

print(f'The number is {num:\<15,.2f}')

*The number is 12,345.68*

print(f'The number is {num:\>15,.2f}')

*The number is 12,345.68\_\_\_ \_\_*

print(f'The number is {num:\^15,.2f}’)

*The number is \_\_\_ 12,345.68 \_\_\_*

## Displaying Formatted Output With f-Strings (8 of 8)

- **The order of designators in a format specifier**

  - When using multiple designators in a format specifier, write them in this order:

\[*alignment*\]\[*width*\]\[,\]\[.*precision*\]\[*type*\]

- **Example:**

  - print(f'{number:\^10,.2f}')

## String Methods (1 of 7)

- **Strings in Python have many types of methods, divided into different types of operations**

  - General format:

*mystring*.*method*(*arguments*)

- **Some methods test a string for specific characteristics**

  - Generally Boolean methods, that return True if a condition exists, and False otherwise

## String Methods (2 of 7)

**Table 8-1** Some string testing methods

| **Method** | **Description** |
|------------------------------------|------------------------------------|
| isalnum() | Returns true if the string contains only alphabetic letters or digits and is at least one character in length. Returns false otherwise. |
| isalpha() | Returns true if the string contains only alphabetic letters and is at least one character in length. Returns false otherwise. |
| isdigit() | Returns true if the string contains only numeric digits and is at least one character in length. Returns false otherwise. |
| islower() | Returns true if all of the alphabetic letters in the string are lowercase, and the string contains at least one alphabetic letter. Returns false otherwise. |
| isspace() | Returns true if the string contains only whitespace characters and is at least one character in length. Returns false otherwise. (Whitespace characters are spaces, newlines (\\n), and tabs (\\t). |
| isupper() | Returns true if all of the alphabetic letters in the string are uppercase, and the string contains at least one alphabetic letter. Returns false otherwise. |

## String Methods (3 of 7)

- **Some methods return a copy of the string, to which modifications have been made**

  - Simulate strings as mutable objects

- **String comparisons are case-sensitive**

  - Uppercase characters are distinguished from lowercase characters
  - lower and upper methods can be used for making case-insensitive string comparisons

## String Methods (4 of 7)

**Table 8-2** String Modification Methods

| **Method** | **Description** |
|------------------------------------|------------------------------------|
| lower() | Returns a copy of the string with all alphabetic letters converted to lowercase. Any character that is already lowercase, or is not an alphabetic letter, is unchanged. |
| lstrip() | Returns a copy of the string with all leading whitespace characters removed. Leading whitespace characters are spaces, newlines (\\n), and tabs (\\t) that appear at the beginning of the string. |
| lstrip(*char*) | The *char* argument is a string containing a character. Returns a copy of the string with all instances of *char* that appear at the beginning of the string removed. |
| rstrip() | Returns a copy of the string with all trailing whitespace characters removed. Trailing whitespace characters are spaces, newlines(\\n), and tabs (\\t) that appear at the end of the string. |
| rstrip(*char*) | The *char* argument is a string containing a character. The method returns a copy of the string with all instances of *char* that appear at the end of the string removed. |
| strip() | Returns a copy of the string with all leading and trailing whitespace characters removed. |
| strip(*char*) | Returns a copy of the string with all instances of *char* that appear at the beginning and the end of the string removed. |
| upper() | Returns a copy of the string with all alphabetic letters converted to uppercase. Any character that is already uppercase, or is not an alphabetic letter, is unchanged. |

## String Methods (5 of 7)

- **Programs commonly need to search for substrings**

- **Several methods to accomplish this:**

  - **endswith(*substring*)**: checks if the string ends with *substring*

    - Returns True or False

  - **startswith(*substring*)**: checks if the string starts with *substring*

    - Returns True or False

## String Methods (6 of 7)

- **Several methods to accomplish this (cont’d):**

  - **find(*substring*)**: searches for *substring* within the string

    - Returns lowest index of the substring, or if the

substring is not contained in the string, returns

Equation

- **replace(*substring*,** ***new_string*****)**:

  - Returns a copy of the string where every occurrence of *substring* is replaced with *new_string*

## String Methods (7 of 7)

**Table 8-3** Search and replace methods

| **Method** | **Description** |
|------------------------------------|------------------------------------|
| endswith(*substring*) | The *substring* argument is a string. The method returns true if the string ends with *substring*. |
| find (*substring*) | The *substring* argument is a string. The method returns the lowest index in the string where *substring* is found. If *substring* is not found, the method returns negative 1 |
| replace(*old, new*) | The *old* and *new* arguments are both strings. The method returns a copy of the string with all instances of *old* replaced by *new*. |
| startswith (*substring*) | The *substring* argument is a string. The method returns true if the string starts with *substring.* |

Equation

## The Repetition Operator

- **Repetition operator: makes multiple copies of a string and joins them together**

  - The \* symbol is a repetition operator when applied to a string and an integer

    - String is left operand; number is right

  - General format: *string_to_copy* \* *n*

  - Variable references a new string which contains multiple copies of the original string

## Splitting a String (1 of 2)

- **split method: returns a list containing the words in the string**

  - By default, uses space as separator
  - Can specify a different separator by passing it as an argument to the split method

## Splitting a String (2 of 2)

- **Examples:**

\>\>\> my_string = 'One two three four'

\>\>\> word_list = my_string.split()

\>\>\> word_list

\['One', 'two', 'three', 'four'\]

\>\>\>

\>\>\> my_string = '1/2/3/4/5'

\>\>\> number_list = my_string.split('/')

\>\>\> number_list

\['1', '2', '3', '4', '5'\]

\>\>\>

## String Tokens (1 of 4)

- **Sometimes a string contains substrings that are separated by a special character**

  - Example:

'peach raspberry strawberry vanilla'

- This string contains the substrings **peach**, **raspberry**, **strawberry**, and **vanilla**
- The substrings are separated by the space character
- The substrings are known as **tokens** and the separating character is known as the **delimiter**

## String Tokens (2 of 4)

- **Example:**

'17;92;81;12;46;5'

- This string contains the tokens 17, 92, 81, 12, 46, and 5
- The delimiter is the ; character

## String Tokens (3 of 4)

- **Tokenizing** is the process of breaking a string into tokens
- When you tokenize a string, you extract the tokens and store them as individual items
- In Python you can use the split method to tokenize a string

## String Tokens (4 of 4)

- **Examples:**

\>\>\> str = 'peach raspberry strawberry vanilla'

\>\>\> tokens = str.split()

\>\>\> tokens

\['peach', 'raspberry', 'strawberry', 'vanilla'\]

\>\>\>

\>\>\> my_address = 'www.example.com'

\>\>\> tokens = my_address.split('.')

\>\>\> tokens

\['www', 'example', 'com'\]

\>\>\>

## Multidimensional Variables

- In Python, variables can store more than a single piece of information.

  - These are **multidimensional** variables.

- We have already seen an example of a multidimensional variable, the **string** data type*.*

  - Recall that a string is a **sequence of characters.**

- Each character in the sequence can be accessed and manipulated independently from any other character.

## Lists

- The most common multidimensional variable in Python is the list.

- Lists are ordered collections of values.

  - Duplicates are allowed.
  - You may have different types of data present in a single list.

- We use the order built into a list to access and alter the different values.

## Creating a List

- Lists are created using the **square brackets** \[ \]
- Separate multiple items in a list using a comma.

A_List = \[ \] #This is an empty list

B_List = \[ 1 , 2 \] #This list contains integers 1 and 2

## Accessing Elements in a List

- Items within a list are often referred to as **elements**.

- Use the square brackets \[ \] after the name of the list to reference the location of the desired element.

- Why ‘b’?

  - Python starts counting from 0.
  - Element 1 is then at the **second** position.

C_List = \[ ‘a’ , ‘b’ , ‘c’ \]

C_List\[1\]

\>\> ‘b’

## Accessing Elements in a List

C_List = \[ ‘x’ , ‘y’ , ‘z’ \]

C_List\[0\]

\>\> ‘x’

C_List\[1\]

\>\> ‘y’

C_List\[2\]

\>\> ‘z’

## Adding Elements to a List

- Adding new elements to a list in Python is most often accomplished using one of two ways.

- The **insert** function adds an item to a specific index (location).

  - **insert(index,value)**

- The append function adds an item directly to the end of the list.

  - **append(value)**
  - Adding an item to the end of a list is a very common operation, so it was given its own dedicated function.

## Example - Insert

C_List = \[ ‘x’ , ‘y’ , ‘z’ \]

C_List.insert(0,’a’)

\>\> print(C_List)

\[ ‘a’, ‘x’ , ‘y’ , ‘z’ \]

## Example - Append

C_List = \[ ‘x’ , ‘y’ , ‘z’ \]

C_List.append(’a’)

\>\> print(C_List)

\[ ‘x’ , ‘y’ , ‘z’, ‘a’ \]

## Practice

- Define a list called *items* that contains the letters a, b, c, and d.
- Add the number 1 at index 2 of *items*.
- Add the number 7 at the end of *items*.
- Print the list *items*.

## Removing Elements from a List

- Removing elements from a list can be accomplished by using the **pop()** function.

- The **pop** function can be used in two different ways.

- Removing an element at a specified index.

  - **pop(index)**

- Removing an element at the end of the list.

  - **pop()**

- By omitting the index from the **pop** function, Python automatically assumes you want to remove the last item in the list.

## Example

C_List = \[ ‘x’ , ‘y’ , ‘z’ \]

C_List.pop(0)

\>\> print(C_List)

\[ ‘y’ , ‘z’ \]

## Example

C_List = \[ ‘x’ , ‘y’ , ‘z’ \]

C_List.pop()

\>\> print(C_List)

\[ ‘x’ , ‘y’ \]

## Practice

- Define a list called *items* that contains the letters a, b, c, and d.
- Remove letter b from *items*.
- Remove the last letter from *items*.
- Print the list *items*.

## Removing Elements from a List

- Removing elements from a list can also be accomplished by using the **del** keyword.

  - Unlike **pop()**, **del** does not return the item that was removed.

- The **del** operation removes an element at a specified index.

  - **del\[index\]**

- Note that the **del** operation uses the square brackets instead of the parenthesis.

- The del operation can also be used to completely delete a list.

  - **del my_list**

## Calculating the Length of a List

- A common operation in programming is calculating the number of elements in a list.

- In Python this is termed the *length* of a list.

- Python has a built-in function to calculate a list’s length

  - **len**(**list**)

- This function returns the number of total elements as an integer.

## List Slicing

- **Slice: a span of items that are taken from a sequence**

  - List slicing format: *list*\[*start* : *end*\]

  - Span is a list containing copies of elements from *start* up to, but not including, *end*

    - If *start* not specified, 0 is used for start index
    - If *end* not specified, len(list) is used for end index

  - Slicing expressions can include a step value and negative indexes relative to end of list

## Tuples (1 of 4)

- **Tuple: an immutable sequence**

  - Similar to a list

  - Tuples are immutable. Once a tuple is created:

    - New elements cannot be added to the tuple
    - Elements cannot be removed from the tuple

## Tuples (2 of 4)

- **Creating a Tuple**

  - my_tuple= (*item1*, *item2*)
  - my_tuple= (*item1*,)

- **Tuples support many list operations**

  - Subscript indexing for retrieving elements
  - Methods such as index
  - Built in functions such as len, min, max
  - Slicing expressions
  - The in, +, and \* operators

## Tuples (3 of 4)

- **Tuples do not support the methods:**

  - append
  - remove
  - insert
  - reverse
  - sort

## Tuples (4 of 4)

- **Reasons for using tuples:**

  - Processing tuples is faster than processing lists

  - Tuples provide safety:

    - no elements can be added to or deleted from a tuple
    - once a tuple is created, the elements of the tuple will always refer to the same objects

  - Some operations in Python require use of tuples

- **list() function: converts tuple to list**

- **tuple() function: converts list to tuple**

## Storing Mutable Objects in a Tuple (1 of 2)

- Although tuples are immutable, you can store mutable objects in a tuple.

  - For example, the following statement creates a tuple that contains a list as its 3rd element:

t = (10, 20, \[97, 98, 99\])

A computer code and a diagram. For long description in Notes pane, press F6.

> A code statement reads, t = left parenthesis 1 comma 20 comma left bracket 97 comma 98 comma 99 right bracket right parenthesis. A diagram illustrates the process of storing mutable objects in a tuple. t references a tuple, which has three parts. The first part stores integer value 10. The second part stores integer value 20. The third part stores a list with integer values, from left to right, 97, 98, 99.

## Storing Mutable Objects in a Tuple (2 of 2)

- When a tuple element refers to a mutable object, that object's data can be changed.

\>\>\> t = (10, 20, \[97, 98, 99\])

\>\>\> print(t)

(10, 20, \[97, 98, 99\])

\>\>\>

\>\>\> t\[2\].append(100)

\>\>\> print(t)

(10, 20, \[97, 98, 99, 100\])

\>\>\>