---
title: "14: Sets"
format: html
---

## 

## Sets

CSCI – 1056

Content Modified from Pearson’s Starting Out with Python 6th Edition

## Sets

- **Set: object that stores a collection of data in same way as mathematical set**

  - All items must be unique
  - Set is unordered
  - Elements can be of different data types

## Creating a Set

- **set function: used to create a set**

  - For empty set, call set()

  - For non-empty set, call set(*argument*) where *argument* is an object that contains iterable elements

    - e.g., *argument* can be a list, string, or tuple

    - If *argument* is a string, each character becomes a set element

      - For set of strings, pass them to the function as a list

    - If *argument* contains duplicates, only one of the duplicates will appear in the set

## Example

*numbers = set(list(range(1,6)))*

*print(numbers)*

*\> {1, 2, 3, 4, 5}*

## Getting the Number of and Adding Elements

- **len function: returns the number of elements in the set**

- **Sets are mutable objects**

- **add method: adds an element to a set**

- **update method: adds a group of elements to a set**

  - Argument must be a sequence containing iterable elements, and each of the elements is added to the set

## Example

*numbers = set(list(range(1,6)))*

*print(numbers)*

*\> {1, 2, 3, 4, 5}*

*numbers.add('six’)*

*print(numbers)*

*\> {1, 2, 3, 4, 5, 'six'}*

## Example

*numbers = set(list(range(1,6)))*

*print(numbers)*

*\> {1, 2, 3, 4, 5}*

*numbers.update(\['six','seven',8, 9\])*

*print(numbers)*

*\> {1, 2, 3, 4, 5, 'seven', 8, 9, 'six'}*

> The order you see from the print statement will often change if you rerun the code. Remember that sets have no inherent order, this is just a visual representation of the contents.

## Deleting Elements From a Set

- **remove and discard methods: remove the specified item from the set**

  - The item that should be removed is passed to both methods as an argument

  - Behave differently when the specified item is not found in the set

    - remove method raises a KeyError exception
    - discard method does not raise an exception

- **clear method: clears all the elements of the set**

## Example

*numbers = set(list(range(1,6)))*

*numbers.remove(1)*

*print(numbers)*

*\> {2, 3, 4, 5}*

*numbers.remove(6)*

*print(numbers)*

*\> KeyError: 6*

## Example

*numbers = set(list(range(1,6)))*

*numbers.discard(1)*

*print(numbers)*

*\> {2, 3, 4, 5}*

*numbers.discard(6)*

*print(numbers)*

*\>*

## Using the for Loop, in, and not in Operators With a Set

- **A for loop can be used to iterate over elements in a set**

  - General format: for *item* in *set*:
  - The loop iterates once for each element in the set

- **The in operator can be used to test whether a value exists in a set**

  - Similarly, the not in operator can be used to test whether a value does not exist in a set

## Example

*numbers = set(list(range(1,6)))*

*for i in numbers:*

*print(i)*

*\> 1*

*\> 2*

*\> 3*

*\> 4*

*\> 5*

## Finding the Union of Sets

- **Union of two sets: a set that contains all the elements of both sets**

- **To find the union of two sets:**

  - Use the union method

    - Format: *set1*.union(*set2*)

  - Use the \| operator

    - Format: *set1* \| *set2*

  - Both techniques return a new set which contains the union of both sets

## Example

*A = {1,2,3}*

*B = {2,3,4}*

*print(A \| B)*

*\> {1, 2, 3, 4}*

## Finding the Intersection of Sets

- **Intersection of two sets: a set that contains only the elements found in both sets**

- **To find the intersection of two sets:**

  - Use the intersection method

    - Format: *set1*.intersection(*set2*)

  - Use the & operator

    - Format: *set1* & *set2*

  - Both techniques return a new set which contains the intersection of both sets

## Example

*A = {1,2,3}*

*B = {2,3,4}*

*print(A & B)*

*\> {2, 3}*

## Finding the Difference of Sets

- **Difference of two sets: a set that contains the elements that appear in the first set but do not appear in the second set**

- **To find the difference of two sets:**

  - Use the difference method

    - Format: *set1*.difference(*set2*)

  - Use the - operator

    - Format: *set1* - *set2*

## Example

*A = {1,2,3}*

*B = {2,3,4}*

*print(A - B)*

*\> {1}*

## Finding the Symmetric Difference of Sets

- **Symmetric difference of two sets: a set that contains the elements that are not shared by the two sets**

- **To find the symmetric difference of two sets:**

  - Use the symmetric_difference method

    - Format: *set1*.symmetric_difference(*set2*)

  - Use the \^ operator

    - Format: *set1* \^ *set2*

## Example

*A = {1,2,3}*

*B = {2,3,4}*

*print(A \^ B)*

*\> {1, 4}*

## Finding Subsets and Supersets (1 of 2)

- **Set A is subset of set B if all the elements in set A are included in set B**

- **To determine whether set A is subset of set B**

  - Use the issubset method

    - Format: *setA*.issubset(*setB*)

  - Use the \<= operator

    - Format: *setA* \<= *setB*

## Example

*A = {1,2,3}*

*B = {3,4}*

*print(B \<= A)*

*\> False*

## Example

*A = {1,2,3}*

*B = {3}*

*print(B \<= A)*

*\> True*

## Finding Subsets and Supersets (2 of 2)

- **Set A is superset of set B if it contains all the elements of set B**

- **To determine whether set A is superset of set B**

  - Use the issuperset method

    - Format: *setA*.issuperset(*setB*)

  - Use the \>= operator

    - Format: *setA* \>= *setB*

## Example

*A = {1,2,3}*

*B = {3,4}*

*print(A \>= B)*

*\> False*

## Example

*A = {1,2,3}*

*B = {3}*

*print(A \>= B)*

*\> True*

## Set Comprehensions (1 of 4)

- Set comprehension: a concise expression that creates a new set by iterating over the elements of a sequence
- Set comprehensions are written just like list comprehensions, except that a set comprehension is enclosed in curly braces ({}) instead of brackets (\[\])

## Set Comprehensions (2 of 4)

- **Example: making a copy of a set**

\>\>\> set1 = set(\[1, 2, 3, 4, 5\])

\>\>\> set2 = {item for item in set1}

\>\>\> set2

{1, 2, 3, 4, 5}

\>\>\>

## Set Comprehensions (3 of 4)

- **Example: creating a set that contains the squares of the numbers stored in another set**

\>\>\> set1 = set(\[1, 2, 3, 4, 5\])

\>\>\> set2 = {item\*\*2 for item in set1}

\>\>\> set2

{1, 4, 9, 16, 25}

\>\>\>

## Set Comprehensions (4 of 4)

- **Example: copying the numbers in a set that are less than 10**

\>\>\> set1 = set(\[1, 20, 2, 40, 3, 50\])

\>\>\> set2 = {item for item in set1 if item \< 10}

\>\>\> set2

{1, 2, 3}

\>\>\>