{
  "hash": "27e72756c8c5b0dc3c8612a28e74fe7f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"14: Pandas\"\nformat: html\n---\n\n# Pandas\n\nWe have seen that NumPy requires pure, homogeneous numbers. Remember that if we put a word into a NumPy array, it converts our numbers to text. But real data is messy, labeled, and heterogeneous.\n\nWe need a solution to intake data, then prepare it for use with libraries that perform calculations (like NumPy). This solution is Pandas, which is an industry-standard library for data ingestion and cleaning.\n\nPandas does not replace NumPy; they serve different roles. - Pandas prepares the data. - NumPy solves the equations.\n\nAs Pandas is an external library, we will need to import it to use it (and depending on your environment, it may need to be installed first).\n\n::: {#0d020652 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n```\n:::\n\n\n## DataFrames\n\nThe core component of Pandas is the **DataFrame** which is a 2D array (a matrix) with attached row and column labels. Each column can hold a *different* type of data without breaking the others.\n\nWe load our data using one of the Pandas methods depending on our file type, and Pandas will do the work of figuring out what the datatypes of the individual columns should be.\n\nAn example of the first few items a DataFrame\n\n|     | Row ID | Order ID       | Order Date | ... | Quantity | Discount | Profit    |\n|-----|--------|----------------|------------|-----|----------|----------|-----------|\n| 0   | 1      | CA-2017-152156 | 11/8/2017  | …   | 2.0      | 0.00     | 41.9136   |\n| 1   | 2      | CA-2017-152156 | 11/8/2017  | …   | 3.0      | 0.00     | 219.5820  |\n| 2   | 3      | CA-2017-138688 | 6/12/2017  | …   | 2.0      | 0.00     | 6.8714    |\n| 3   | 4      | US-2016-108966 | 10/11/2016 | …   | 5.0      | 0.45     | -383.0310 |\n| 4   | 5      | US-2016-108966 | 10/11/2016 | …   | 2.0      | 0.20     | 2.5164    |\n\n### Loading Data\n\nTo load data into a DataFrame, we first need to know what file type we are working with. Commonly, this is a CSV file (Comma Separated Values)\n\nWe then need to know where the file is located. This could be a file path on your computer or even a URL.\n\n```         \nimport pandas as pd\n\nurl = \"[https://website/data.csv\"](https://website/data.csv%22)\n\ndf = pd.read_csv(url)\n```\n\nFor many of our examples we will use a CSV file (Tableau’s Sample Superstore dataset) that can be found on Blackboard. Assuming we have named the file `superstore.csv` we can use the following code to load the data into a DataFrame named `df`.\n\n::: {#79d48119 .cell execution_count=2}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_csv('superstore.csv')\n```\n:::\n\n\n### Inspecting Data\n\nThe example DataFrame from earlier was from the superstore dataset and the data we saw was output from the `head()` method which returns (by default) the first 5 rows of the data in the DataFrame.\n\nThe `head` method (and its counterpart, `tail`) are important first steps after you load data using Pandas. You should never trust unseen data, as there are often missing entries, mislabeled columns, wrong data values, etc.\n\n::: {#1163803d .cell execution_count=3}\n``` {.python .cell-code}\ndf = pd.read_csv('superstore.csv')\n\nprint(df.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \\\n0      1  CA-2017-152156   11/8/2017  11/11/2017    Second Class    CG-12520   \n1      2  CA-2017-152156   11/8/2017  11/11/2017    Second Class    CG-12520   \n2      3  CA-2017-138688   6/12/2017   6/16/2017    Second Class    DV-13045   \n3      4  US-2016-108966  10/11/2016  10/18/2016  Standard Class    SO-20335   \n4      5  US-2016-108966  10/11/2016  10/18/2016  Standard Class    SO-20335   \n\n     Customer Name    Segment        Country             City  ...  \\\n0      Claire Gute   Consumer  United States        Henderson  ...   \n1      Claire Gute   Consumer  United States        Henderson  ...   \n2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   \n3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   \n4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   \n\n  Postal Code  Region       Product ID         Category Sub-Category  \\\n0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases   \n1     42420.0   South  FUR-CH-10000454        Furniture       Chairs   \n2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels   \n3     33311.0   South  FUR-TA-10000577        Furniture       Tables   \n4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage   \n\n                                        Product Name     Sales  Quantity  \\\n0                  Bush Somerset Collection Bookcase  261.9600       2.0   \n1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400       3.0   \n2  Self-Adhesive Address Labels for Typewriters b...   14.6200       2.0   \n3      Bretford CR4500 Series Slim Rectangular Table  957.5775       5.0   \n4                     Eldon Fold 'N Roll Cart System   22.3680       2.0   \n\n   Discount    Profit  \n0      0.00   41.9136  \n1      0.00  219.5820  \n2      0.00    6.8714  \n3      0.45 -383.0310  \n4      0.20    2.5164  \n\n[5 rows x 21 columns]\n```\n:::\n:::\n\n\n- We can see not all the columns are visible (…) due to visual size limitations.\n\n|     | Row ID | Order ID       | Order Date | ... | Quantity | Discount | Profit    |\n|-----|--------|----------------|------------|-----|----------|----------|-----------|\n| 0   | 1      | CA-2017-152156 | 11/8/2017  | …   | 2.0      | 0.00     | 41.9136   |\n| 1   | 2      | CA-2017-152156 | 11/8/2017  | …   | 3.0      | 0.00     | 219.5820  |\n| 2   | 3      | CA-2017-138688 | 6/12/2017  | …   | 2.0      | 0.00     | 6.8714    |\n| 3   | 4      | US-2016-108966 | 10/11/2016 | …   | 5.0      | 0.45     | -383.0310 |\n| 4   | 5      | US-2016-108966 | 10/11/2016 | …   | 2.0      | 0.20     | 2.5164    |\n\nThe number of columns and rows displayed by head / tail can be adjusted using settings in Pandas. However, some datasets will be large enough that you will not have enough display space to visually inspect everything. The `head` and `tail` provides the total number of columns (even if they are not displayed) and the total number of currently displayed rows.\n\nRow ID Order ID Order Date ... Quantity Discount Profit\n\n0 1 CA-2017-152156 11/8/2017 ... 2.0 0.00 41.9136\n\n…\n\n\\[5 rows x 21 columns\\]\n\nWhile `head` / `tail` give us the total number of columns, they do not provide the total number of rows. We can use the `shape` attribute to return both the number of rows and number of columns.\n\n::: {#ee8b949f .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_csv('superstore.csv')\n\nprint(df.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(10800, 21)\n```\n:::\n:::\n\n\n\\>\\>\\> (10800, 21)\n\n- **dtypes** tells us the data type of each column\n\n- Float64 specifies a floating-point number.\n\n- Object is a general non-numeric type (often a string).\n\nRow ID object\n\nOrder ID object\n\nOrder Date object\n\n… …\n\nSub-Category object\n\nProduct Name object\n\nSales float64\n\nQuantity float64\n\nDiscount float64\n\nProfit float64\n\nimport pandas as pd\n\ndf = pd.read_csv('superstore.csv’)\n\nprint(df.dtypes)\n\n- **describe()** gives us summary statistics on columns with a numeric data type.\n\n- The statistics are:\n\n  - count (the number of non-empty cells)\n\n    - The values **None**, **NaN**, **NaT**, **pandas.NA** are considered “empty”\n    - **NaN**: not a number, **NaT**: not a time\n\n  - mean\n\n  - standard deviation\n\n  - min (smallest value)\n\n  - 25%, 50%, 75% (percentiles)\n\n  - max (largest value)\n\n- **describe()** gives us summary statistics on every column even if it does not make sense in context (the mean of the postal codes is meaningless).\n\nPostal Code Sales Quantity Discount Profit\n\ncount 9983.000000 9994.000000 9994.000000 9994.000000 9994.000000\n\nmean 55245.233297 229.858001 3.789574 0.156203 28.656896\n\nstd 32038.715955 623.245101 2.225110 0.206452 234.260108\n\nmin 1040.000000 0.444000 1.000000 0.000000 -6599.978000\n\n25% 23223.000000 17.280000 2.000000 0.000000 1.728750\n\n50% 57103.000000 54.490000 3.000000 0.200000 8.666500\n\n75% 90008.000000 209.940000 5.000000 0.200000 29.364000\n\nmax 99301.000000 22638.480000 14.000000 0.800000 8399.976000\n\n- **describe()** is very useful for finding impossible values.\n- For example, assume we have a DataFrame of sensor readings with one of the columns being temperature.\n- If we see negative values in the temperature column, we know the data is erroneous.\n\n## Extracting and Manipulating Data\n\n### Extracting Columns\n\n- Extract a single column (1D Series) using one set of brackets:\n\n\\[‘Column_Name’\\]\n\n- Extract a sub-matrix (2D DataFrame) using a list of columns:\n\n\\[\\[‘Column_Name_1’, ‘Column_Name_2’\\]\\]\n\n- A DataFrame is a dictionary of column vectors, so case matters for the column names.\n\n## Extracting Columns\n\ndf\\[‘Discount’\\]\n\n0 0.00\n\n1 0.00\n\n... ...\n\n10798 NaN\n\n10799 NaN\n\nName: Discount, Length: 10800, dtype: float64\n\ndf\\[‘Discount’,’Profit’\\]\n\nDiscount Profit\n\n0 0.00 41.9136\n\n1 0.00 219.5820\n\n... ...\n\n10798 NaN NaN\n\n10799 NaN NaN\\\n\n\\[10800 rows x 2 columns\\]\n\n### Renaming Columns\n\n- Raw data often has terrible names (e.g., \"Temp (C) - Sensor 1!\").\n- Use .rename() and a dictionary to fix them before writing logic.\n\n\\# Syntax: columns={'old_name': 'new_name’}\n\ndf = df.rename(columns={'Temp (C)': 'Temp',\n\n'Press_kpa': 'Pressure'})\n\n### Filtering Rows (Boolean Masking)\n\n- We can apply the exact same relational logic (\\>, \\<, ==) to a Pandas column.\n- This creates a \"mask\" of True/False values to filter the DataFrame.\n\n\\# Find all rows where Temperature is over 100\n\ndanger_mask = df\\['Temp'\\] \\> 100\n\n\\# Apply the mask to the DataFrame\n\ndanger_data = df\\[danger_mask\\]\n\n\\# Do it in one line:\n\ndanger_data = df\\[df\\['Temp'\\] \\> 100\\]\n\n### Combining Logic (AND / OR)\n\n- To find specific overlaps, use & (AND) and \\| (OR).\n- **Very Important:** You *must* put parentheses around each condition.\n\n\\# Find Discounts AND Negative Profit\n\nlosses = df\\[(df\\[‘Discount'\\] \\> 0) & (df\\[‘Profit'\\] \\< 0)\\]\n\nRow ID Order ID Order Date ... Quantity Discount Profit\n\n3 4 US-2016-108966 10/11/2016 ... 5.0 0.45 -383.0310\n\n14 15 US-2016-118983 11/22/2016 ... 5.0 0.80 -123.8580\n\n…\n\n### Sorting\n\n- Sorting data sequentially in Pandas is very simple.\n\n- **.sort_values()** orders the matrix by a specific column.\n\n  - The column is specified using the **by** parameter\n  - You can adjust sorting by ascending/descending order by setting the Boolean on the **ascending** parameter.\n\n\\# Sort from highest profit to lowest\n\nsorted_data = df.sort_values(by=‘Profit', ascending=False)\n\n\\# View the top 3 most profitable rows\n\nprint(sorted_data.head(3))\n\n### Handling Missing Data\n\n- **NaN** stands for \"Not a Number\" (a blank cell in the CSV).\n\n  - We mentioned other versions earlier like **NaT** (Not a Time)\n\n- In general, you cannot do mathematics with missing data.\n\n  - Calculations that involve **NaN** resolve to **NaN**.\n  - Calculations that involve **None** throw an exception.\n\n- **.dropna()** removes any row containing a **NaN**.\n\n- The safest decision is to drop the corrupted observation entirely.\n\n- There exist methods to interpolate the missing value(s), but these should be used cautiously.\n\n\\# See how many missing values exist\n\nprint(df.isna().sum())\n\n\\# Drop the corrupted rows permanently\n\ndf = df.dropna()\n\n## Calculated Columns (Pandas Vectorization)\n\n- We can create brand new columns using the data we already have.\n- Pandas handles the row-by-row iteration automatically (just like NumPy).\n\n\\# Calculate Power (P = V \\* I)\n\ndf\\['Power_Watts'\\] = df\\['Voltage'\\] \\* df\\['Current'\\]\n\n## Calculated Columns (Pandas Vectorization)\n\n- Using calculated columns is much cleaner than writing a for loop to iterate through thousands of rows.\n\ndf\\['Profit_Per_Unit'\\] = df\\['Profit'\\] / df\\['Quantity’\\]\n\nprint(df.head())\n\nRow ID Order ID Order Date ... Discount Profit Profit_Per_Unit\n\n0 1 CA-2017-152156 11/8/2017 ... 0.00 41.9136 20.9568\n\n1 2 CA-2017-152156 11/8/2017 ... 0.00 219.5820 73.1940\n\n2 3 CA-2017-138688 6/12/2017 ... 0.00 6.8714 3.4357\n\n3 4 US-2016-108966 10/11/2016 ... 0.45 -383.0310 -76.6062\n\n4 5 US-2016-108966 10/11/2016 ... 0.20 2.5164 1.2582\n\n## Text Scrubbing\n\n- Sometimes numbers are accidentally imported as strings because of symbols (e.g., \"\\$1,000\").\n- We use **.str** to access string methods, and **.astype()** to cast them back to numbers.\n\n\\# 1. Replace the comma with nothing\n\ndf\\['Cost'\\] = df\\['Cost'\\].str.replace(',', '')\n\n\\# 2. Strip accidental blank spaces\n\ndf\\['Cost'\\] = df\\['Cost'\\].str.strip()\n\n\\# 3. Convert the clean text back into a float for math\n\ndf\\['Cost'\\] = df\\['Cost'\\].astype(float)\n\n## Time and Dates\n\n- Python reads dates as \"dumb\" strings by default.\n- **pd.to_datetime()** converts them into \"smart\" timestamps.\n- The **.dt** accessor extracts specific features (month, year, day of week).\n\n\\# Convert the string column to datetime objects\n\ndf\\['Date'\\] = pd.to_datetime(df\\['Date_String'\\])\n\n\\# Extract the month as a new numeric column (1-12)\n\ndf\\['Month'\\] = df\\['Date'\\].dt.month\n\n## Aggregation\n\n- How do we find the average profit per day?\n\n- Or the postal code with the highest number of total sales?\n\n- We can use the **groupby()** method, likely the most powerful single tool in Pandas**.**\n\n- The process has three steps:\n\n  - Split the data into categories.\n  - Apply math.\n  - Combine the results.\n\n## Aggregation\n\n\\# Drop rows where the date column is NaT\n\ndf = df.dropna(subset=\\['Order Date’\\])\n\nappd = df.groupby('Order Date')\\['Profit'\\].mean() #average profit per day\n\nprint(appd.head())\n\nOrder Date\n\n2015-01-03 5.551200\n\n2015-01-04 -21.996700\n\n2015-01-05 4.884000\n\nName: Profit, dtype: float64\n\n## Aggregation\n\n#Find the top 3 area codes by total sales\n\nappd = df.groupby('Postal Code')\\['Sales'\\].sum().nlargest(3)\n\nprint(appd.head())\n\nPostal Code\n\n10024.0 78697.182\n\n10035.0 77357.885\n\n10009.0 54761.496\n\nName: Sales, dtype: float64\n\n## Aggregation\n\n- We see that the Postal Codes here are floats.\n\n  - It is an identifier and not a quantity, so it is a good idea to change the type.\n\n- We can fix this using the **astype** function and casting as an integer.\n\nPostal Code\n\n0 42420.0\n\n1 42420.0\n\n2 90036.0\n\nName: Postal Code, dtype: float64\n\n## Aggregation\n\n- We see that the Postal Codes here are floats.\n\n  - It is an identifier and not a quantity, so it is a good idea to change the type.\n\n- We can fix this using the **astype** function and casting as an integer.\n\ndf\\['Postal Code'\\] = df\\['Postal Code'\\].astype('Int64')\n\nPostal Code\n\n0 42420\n\n1 42420\n\n2 90036\n\nName: Postal Code, dtype: Int64\n\n## Aggregation\n\n- \\# Convert a string column to datetime objects\n\n- df\\['Date'\\] = pd.to_datetime(df\\['Date_String'\\])\n\n- \\# Extract the month as a new numeric column (1-12)\n\n- df\\['Month'\\] = df\\['Date'\\].dt.month\n\n## Useful Distinctions\n\n- **Aggregation** (sum(), mean(), count()) computes one value per group.\n\n- **Reduction** (max(), min()) computes one value from the entire Series.\n\n  - A series can be viewed as a single column in the DataFrame.\n\n- **Index retrieval** (idxmax(), idxmin()) tells you *which label* produced that maximum or minimum.\n\n## Performing Mathematics on DataFrames\n\n- More complicated mathematical operations will require you to cast the DataFrame to a NumPy array.\n- This is done using the **.to_numpy()** method.\n- Note that there can be no text or NaN values in the columns that are cast into an array if you want to receive valid output.\n\ndata = df\\['Sales'\\].to_numpy()\n\nprint(data.mean())\n\n## Performing Mathematics on DataFrames\n\n- Simple operations can be done on the DataFrame itself, especially a single series associated with it.\n\nprint(df\\[\"Sales\"\\].mean())\n\n\\>\\>\\>229.85800083049827\n\n## Performing Mathematics on DataFrames\n\n- We can also iterate through using the standard Python for loop syntax.\n- However, Pandas specific operations are both shorter to write and more efficient.\n\n#Also the mean of the sales series\n\ns = 0\n\nfor i in df\\['Sales'\\]:\n\ns += i\n\nprint(s/len(df\\['Sales’\\]))\n\n\\>\\>\\> 229.8580008304938\n\n## Pandas - Continued\n\nCSCI – 1056\n\n## Multiple Aggregations\n\n- Often, we need different math for different columns at the same time.\n- The **.agg()** method takes a dictionary: **{ 'ColumnName': 'math_operation' }**.\n- This can complete enormous tasks in a single computational pass.\n\n#Find the total, average, maximum, and minimum sales by region.\n\nsummary = (\n\ndf.groupby('Region')\\['Sales'\\]\n\n.agg(\\['sum', 'mean', 'max', 'min'\\])\n\n)\n\nprint(summary)\n\n## Different Aggregations for Different Columns\n\n- We can run simultaneous aggregations by passing a dictionary into the **.agg** method.\n\n  - The key is the name of the column, and its value is the operation.\n  - Operations used must accept a series and return a single value.\n\nsummary = (\n\ndf.groupby('Region')\n\n.agg({\n\n'Sales': 'sum',\n\n'Profit': 'mean',\n\n'Discount': 'max',\n\n'Quantity': 'sum’}))\n\n## Different Aggregations for Different Columns\n\nsummary = (\n\ndf.groupby('Region')\n\n.agg({\n\n'Sales': 'sum',\n\n'Profit': 'mean',\n\n'Discount': 'max',\n\n'Quantity': 'sum’}))\n\nSales Profit Discount Quantity\n\nRegion\n\nCentral 501239.8908 17.092709 0.8 8780.0\n\nEast 678781.2400 32.135808 0.7 10618.0\n\nSouth 391721.9050 28.857673 0.7 6209.0\n\nWest 725457.8245 33.849032 0.7 12266.0\n\n## Different Aggregations for Different Columns\n\n- You are not limited to pre-built aggregation functions.\n- You can define operations yourself by creating a function that accepts a Pandas series and returns a single value.\n\ndef range(series):\n\nreturn series.max() – series.min()\n\n## Different Aggregations for Different Columns\n\n- The issue here is that “Sales” is ambiguous for what we are performing by the aggregation.\n- To make our operations obvious, we can use named aggregations to rename the displayed column names.\n\nsummary = (\n\ndf.groupby('Region')\n\n.agg({\n\n'Sales': range,\n\n}))\n\nSales\n\nRegion\n\nCentral 17499.506\n\nEast 11199.116\n\nSouth 22637.313\n\nWest 13998.970\n\n## Named Aggregations\n\n- We can rename the displayed column names using a variable assignment inside the aggregation.\n\n- **TotalSales=(”Sales”, sum)**\n\n  - The resulting column name of the sum of sales by category is **TotalSales**.\n\nsummary = (\n\ndf.groupby('Category')\n\n.agg(\n\nTotalSales=('Sales', 'sum'),\n\nAvgSale=('Sales', 'mean'),\n\nTotalProfit=('Profit', 'sum'),\n\nAvgProfit=('Profit', 'mean'),\n\nOrders=('Sales', 'count’)\n\n)).round(2)\n\n## Named Aggregations\n\nsummary = (\n\ndf.groupby('Category')\n\n.agg(\n\nTotalSales=('Sales', 'sum'),\n\nAvgSale=('Sales', 'mean'),\n\nTotalProfit=('Profit', 'sum'),\n\nAvgProfit=('Profit', 'mean'),\n\nOrders=('Sales', 'count’)\n\n)).round(2)\n\nTotalSales AvgSale TotalProfit AvgProfit Orders\n\nCategory\n\nFurniture 741999.80 349.83 18451.27 8.70 2121\n\nOffice Supplies 719047.03 119.32 122490.80 20.33 6026\n\nTechnology 836154.03 452.71 145454.95 78.75 1847\n\n## Several Statistics for Several Columns\n\n- We can produce multiple statistics across multiple columns.\n- The same dictionary format is used for the **.agg** method and the value is now a list of operations.\n\nsummary = (\n\ndf.groupby('Category')\n\n.agg({\n\n'Sales': \\['sum', 'mean'\\],\n\n'Profit': \\['sum', 'mean'\\],\n\n'Quantity': \\['sum', 'max'\\]\n\n})).round(2)\n\n## Several Statistics for Several Columns\n\nsummary = (\n\ndf.groupby('Category')\n\n.agg({\n\n'Sales': \\['sum', 'mean'\\],\n\n'Profit': \\['sum', 'mean'\\],\n\n'Quantity': \\['sum', 'max'\\]\n\n})).round(2)\n\nSales Profit\n\nsum mean sum mean Category\n\nFurniture 741999.80 349.83 18451.27 8.70\n\nOffice Supplies 719047.03 119.32 122490.80 20.33\n\nTechnology 836154.03 452.71 145454.95 78.75\n\n## Two-level groupby with Multiple Aggregations\n\n- We want to evaluate the profit, sales, and average discount across the different categories of goods by region.\n- We can include multiple levels in the groupby simply by using a list of series names.\n\nsummary = (\n\ndf.groupby(\\['Region', 'Category'\\])\n\n.agg(\n\nSales=('Sales', 'sum'),\n\nProfit=('Profit', 'sum'),\n\nAvgDiscount=('Discount', 'mean')\n\n)\n\n).round(2)\n\n## Two-level groupby with Multiple Aggregations\n\nsummary = (\n\ndf.groupby(\\['Region', 'Category'\\])\n\n.agg(\n\nSales=('Sales', 'sum'),\n\nProfit=('Profit', 'sum'),\n\nAvgDiscount=('Discount', 'mean')\n\n)\n\n).round(2)\n\nRegion Category\n\nCentral Furniture 163797.16 -2871.05 0.30\n\nOffice Supplies 167026.42 8879.98 0.25\n\nTechnology 170416.31 33697.43 0.13\n\nEast Furniture 208291.20 3046.17 0.15\n\nOffice Supplies 205516.06 41014.58 0.14\n\nTechnology 264973.98 47462.04 0.14\n\n## Which category is most profitable in each region?\n\nsummary = (\n\ndf.groupby(\\['Region', 'Category'\\])\n\n.agg(\n\nTotalSales=('Sales', 'sum'),\n\nTotalProfit=('Profit', 'sum')\n\n)\n\n.sort_values('TotalProfit', ascending=False)\n\n)\n\n## Which category is most profitable in each region?\n\nRegion Category\n\nWest Office Supplies 220853.25 52609.85\n\nEast Technology 264973.98 47462.04\n\nWest Technology 251991.83 44303.65\n\nEast Office Supplies 205516.06 41014.58\n\nCentral Technology 170416.31 33697.43\n\nSouth Technology 148771.91 19991.8\n\nOffice Supplies 125651.31 19986.39\n\nWest Furniture 252612.74 11504.95\n\nCentral Office Supplies 167026.42 8879.98\n\nSouth Furniture 117298.68 6771.21\n\nEast Furniture 208291.20 3046.17\n\nCentral Furniture 163797.16 -2871.05\n\n> The empty space by office supplies is Pandas omitting the identical region name (south) to prevent repeats.\n\n## Reshaping: Pivot Tables\n\n- Sometimes data is too \"tall\" to read easily.\n- **pivot_table** reshapes data to look exactly like an Excel pivot table, turning unique row values into new columns.\n\nmonthly_view = df.pivot_table(\n\nindex='', \\# What stays as rows\n\ncolumns='', \\# What becomes the new columns\n\nvalues='', \\# What fills the cells\n\naggfunc='' \\# How to handle duplicates\n\n)\n\n## Reshaping: Pivot Tables\n\n- We can use pivot tables much the same way as groupby.\n- Both below compute the same summary.\n\ndf.pivot_table(\n\nvalues='Sales',\n\nindex='Region',\n\ncolumns='Category',\n\naggfunc='sum’\n\n)\n\ndf.groupby(\\['Region', 'Category'\\])\\['Sales'\\].sum()\n\n## Reshaping: Pivot Tables\n\n- The difference is in how the result is arranged:\n- **groupby()** leaves both grouping variables in the index (or MultiIndex).\n- **pivot_table()** places one grouping variable into columns, producing a cross-tab that resembles an Excel pivot table.\n\ndf.pivot_table(\n\nvalues='Sales',\n\nindex='Region',\n\ncolumns='Category',\n\naggfunc='sum’\n\n)\n\ndf.groupby(\\['Region', 'Category'\\])\\['Sales'\\].sum()\n\n## Reshaping: Pivot Tables\n\nRegion Category\n\nCentral Furniture 163797.1638\n\nOffice Supplies 167026.4150\n\nTechnology 170416.3120\n\nEast Furniture 208291.2040\n\nOffice Supplies 205516.0550\n\nTechnology 264973.9810\n\nSouth Furniture 117298.6840\n\nOffice Supplies 125651.3130\n\nTechnology 148771.9080\n\nWest Furniture 252612.7435\n\nOffice Supplies 220853.2490\n\nTechnology 251991.8320\n\nName: Sales, dtype: float64\n\nCategory Furniture Office Supplies Technology\n\nRegion\n\nCentral 163797.1638 167026.415 170416.312\n\nEast 208291.2040 205516.055 264973.981\n\nSouth 117298.6840 125651.313 148771.908\n\nWest 252612.7435 220853.249 251991.832\n\n- The **pivot table** below is functionally equivalent to the **groupby** to the right.\n\n- Only the visual presentation differs.\n\n## Reshaping: Pivot Tables\n\n- Multiple values can be used by passing in a list.\n\npivot = df.pivot_table(\n\nvalues=\\['Sales', 'Profit'\\],\n\nindex='Region',\n\ncolumns='Category',\n\naggfunc='sum’\n\n)\n\nProfit Sales\n\nCategory Furniture Office Supplies Technology Furniture Office Supplies Technology\n\nRegion\n\nCentral -2871.05 8879.98 33697.43 163797.16 167026.42 170416.31\n\nEast 3046.17 41014.58 47462.04 208291.20 205516.06 264973.98\n\nSouth 6771.21 19986.39 19991.83 117298.68 125651.31 148771.91\n\nWest 11504.95 52609.85 44303.65 252612.74 220853.25 251991.83\n\n## Reshaping: Pivot Tables\n\n- Passing the margins flag generates an all column and row.\n\npivot = df.pivot_table(\n\nvalues='Sales',\n\nindex='Region',\n\ncolumns='Category',\n\naggfunc='sum',\n\nmargins=True\n\n).round(2)\n\nCategory Furniture Office Supplies Technology All\n\nRegion\n\nCentral 163797.16 167026.42 170416.31 501239.89\n\nEast 208291.20 205516.06 264973.98 678781.24\n\nSouth 117298.68 125651.31 148771.91 391721.90\n\nWest 252612.74 220853.25 251991.83 725457.82\n\nAll 741999.80 719047.03 836154.03 2297200.86\n\n## Reshaping: Melt\n\n- Human generated data is often \"wide\" (e.g., Jan, Feb, Mar as separate columns).\n- **pd.melt()** unpivots data, collapsing multiple columns down into two generic columns: \"Variable\" and \"Value\".\n- Many plotting libraries, statistical tools and SQL databases expect data in the melt format, not the pivot format.\n\ntall_df = pd.melt(\n\nwide_df,\n\nid_vars=\\[’’\\], \\# Columns to lock in place\n\nvar_name='', \\# Name for the columns\n\nvalue_name='' \\# Name for the values\n\n)\n\n## Reshaping: Melt\n\n- The DataFrame resulting from the pivot_table below looks like:\n\nsales = df.pivot_table(\n\nvalues='Sales',\n\nindex='Region',\n\ncolumns='Category',\n\naggfunc='sum'\n\n).reset_index()\n\nCategory Region Furniture Office Supplies Technology\n\n0 Central 163797.1638 167026.415 170416.312\n\n1 East 208291.2040 205516.055 264973.981\n\n2 South 117298.6840 125651.313 148771.908\n\n3 West 252612.7435 220853.249 251991.832\n\n## Reshaping: Melt\n\n- If we wanted one row per Region–Category combination instead:\n\n- **melt()** takes multiple columns and stacks them into two columns: one for the former column names and one for their values.\n\nlong = sales.melt(\n\nid_vars='Region',\n\nvar_name='Category',\n\nvalue_name='Sales'\n\n)\n\n## Reshaping: Melt\n\nRegion Category Sales\n\n0 Central Furniture 163797.1638\n\n1 East Furniture 208291.2040\n\n2 South Furniture 117298.6840\n\n3 West Furniture 252612.7435\n\n4 Central Office Supplies 167026.4150\n\n5 East Office Supplies 205516.0550\n\n6 South Office Supplies 125651.3130\n\n7 West Office Supplies 220853.2490\n\n8 Central Technology 170416.3120\n\n9 East Technology 264973.9810\n\n10 South Technology 148771.9080\n\n11 West Technology 251991.8320\n\n## Concatenation\n\n- **pd.concat()** is used when you have the exact same columns, but new rows of data.\n- Perfect for stacking multiple months, quarters, or batches of data together.\n- Important to reset the index to prevent repeated row numbers.\n\n\\# Stacking Q1 and Q2 data vertically\n\nfull_year_df = pd.concat(\\[q1_data, q2_data\\], axis=0)\n\n\\# Reset the index so row numbers don't repeat\n\nfull_year_df = full_year_df.reset_index(drop=True)\n\n## Merging & Joins\n\n- Merges and joins are among the most important operations in pandas because they allow you to combine information from multiple DataFrames.\n\n- The important question when combining two DataFrames is:\n\n- **How do we know which rows belong together?**\n\n- Pandas answers this by matching values in one or more columns.\n\n  - It can also match on an index, which is the term row label.\n  - Columns contain the actual data values; the index is just for identification.\n\n## Merging & Joins\n\n- **pd.merge()** combines two *different* DataFrames based on a shared column (a \"Key\").\n\n  - This is identical to a SQL JOIN.\n\n- **Left Join:** Keep everything in the left table, attach data from the right table if it matches.\n\n- **Right Join:** Keep everything in the right table, attach data from the left table if it matches.\n\n- **Inner Join:** Keep only rows that appear in both tables.\n\n- **Outer Join:** Keep everything from both tables.\n\n## Merging & Joins\n\n- The basic syntax is:\n\npd.merge(left_df, #Left DataFrame\n\nright_df, #Right DataFrame\n\non=\"ColumnName\", #Column used for matching\n\nhow=\"inner\") #Type of join\n\n## Merging & Joins\n\n- Suppose we have two DataFrames, Customers and Accounts.\n\n**Customers**\\\nCustomerID Name\\\n0 101 Alice\\\n1 102 Bob\\\n2 103 Charlie\\\n3 104 David\n\n**Accounts**\\\nCustomerID Balance\n\n0 101 2500\n\n1 101 1200\n\n2 103 8000\n\n3 105 500\n\n## Inner Join\n\n- An **inner join** keeps only rows that appear in both tables.\n\nmerged = pd.merge(customers,\n\naccounts,\n\non=\"CustomerID\",\n\nhow=\"inner\")\\\n\nCustomerID Name Balance\n\n0 101 Alice 2500\n\n1 101 Alice 1200\n\n2 103 Charlie 8000\n\n## Inner Join\n\n- Notice that Alice appears twice.\n- This is because there are two matching rows in the Accounts table.\n- Inner join is matching every possible pair.\n\n**Customers**\\\nCustomerID Name\\\n0 101 Alice\\\n1 102 Bob\\\n2 103 Charlie\\\n3 104 David\n\n**Accounts**\\\nCustomerID Balance\n\n0 101 2500\n\n1 101 1200\n\n2 103 8000\n\n3 105 500\n\n## Left Join\n\n- A left join keeps **everything from the left table**.\n\nmerged = pd.merge(customers,\n\naccounts,\n\non=\"CustomerID\",\n\nhow=\"left\")\n\n## Left Join\n\n- Since Bob and David have no entry in the right table (accounts) Pandas will insert NaN to fill the empty balance value.\n\nCustomerID Name Balance\n\n0 101 Alice 2500.0\n\n1 101 Alice 1200.0\n\n2 102 Bob NaN\n\n3 103 Charlie 8000.0\n\n4 104 David NaN\n\n## Right Join\n\n- A **right join** keeps everything from the right table.\n\nmerged = pd.merge(customers,\n\naccounts,\n\non=\"CustomerID\",\n\nhow=”right\")\n\n## Right Join\n\n- Customer 105 only exists in the accounts table; Pandas will insert NaN to fill the empty name value.\n\nCustomerID Name Balance\n\n0 101 Alice 2500\n\n1 101 Alice 1200\n\n2 103 Charlie 8000\n\n3 105 NaN 500\n\n## Outer Join\n\n- An **outer join** keeps everything from both tables.\n\nmerged = pd.merge(customers,\n\naccounts,\n\non=\"CustomerID\",\n\nhow=”outer\")\n\n## Outer Join\n\n- Nothing in either table is discarded.\n\nCustomerID Name Balance\n\n0 101 Alice 2500.0\n\n1 101 Alice 1200.0\n\n2 102 Bob NaN\n\n3 103 Charlie 8000.0\n\n4 104 David NaN\n\n5 105 NaN 500.0\n\n## Merging on Different Column Names\n\n- Sometimes the key columns have different names.\n- This is easily handled using the **left_on** and **right_on** parameters.\n\npd.merge(customers,\n\ntransactions,\n\nleft_on=\"CustomerID\",\n\nright_on=\"CustID\")\n\n## Multi-Key Joins\n\n- Sometimes one column is not enough to guarantee a unique match.\n- For example, an Account Number might repeat across different Processing Dates.\n- We can pass a list of columns to the **on** parameter to match on multiple keys simultaneously.\n\npd.merge(df1,\n\ndf2,\n\non=\\[\"CustomerID\", \"Type\"\\])\n\n## Concatenation is Different from Merging\n\n- A common mistake is confusing **merge()** with **concat()**.\n\n- **concat()** stacks DataFrames together.\n\n  - It does **not** match rows.\n\n- If you need to match rows, use **merge()** and specify the type of join.\n\n  - If you want to match by the index (and not the data in the column) use the **join()** method instead.\n  - Matching by index is uncommon, most situations will be by matching columns.\n\n- If you do not need to match rows, use **concat()**.\n\n",
    "supporting": [
      "pandas_files"
    ],
    "filters": [],
    "includes": {}
  }
}